### ISSUE TITLE
Some questions related to the paper

### ISSUE THREAD

**Issue by JIANG-CX** [zhengzhang01/Pixel-GS#2]
Impressive work!
I have come across some questions while reading your paper. The paper states that the large Gaussians are observable from multiple viewpoints, but many of them are only partially covered near the boundaries. Is this occlusion caused by other small Gaussians obstructing the center? If so, why do the small Gaussians seem to have minimal influence from these occlusions?
I would greatly appreciate it if you could provide clarification regarding these inquiries. Thank you for your time and assistance.

**Comment by zhengzhang01** [comment]
Thank you for your interest in our work!

Our paper addresses the following issue: According to Formula 4 in the paper, during the initialization process of 3D Gaussian Splatting (3DGS), the radius of the Gaussian assigned to each point is determined based on the distance to the three nearest points. In regions where the initial Structure-from-Motion (SFM) point cloud is sparse, larger Gaussians are generated to fill these areas.

The original 3DGS determines whether a Gaussian should "split" or "clone" based on whether the average magnitude of the gradient in different Normalized Device Coordinates (NDC) views exceeds a threshold ($\frac{\sum{\parallel \mathbf{g}*i\parallel}}{\sum{1}} > {\tau}*{\mathrm{pos}}$).

We have found that this condition for point cloud growth does not work effectively for larger Gaussians, mainly for the following reason:

1. From a single viewpoint: Larger Gaussians experience severe gradient cancellation between different pixels within the same view. In contrast, even if smaller Gaussians undergo gradient cancellation, due to the mathematical differences in Gaussian distributions across pixels, the magnitude of gradients differs significantly, making the cancellation less severe.
![1](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/359aadf2-e81c-4832-b6f1-e72ea9498a5f)

2. From different viewpoints: Large Gaussians occupy more 3D space and thus involve more viewpoints in the same spatial location compared to smaller Gaussians. However, some of these viewpoints only contribute to the calculations at the edges. Due to the mathematical properties of Gaussian distributions and the occurrence of gradient cancellation, these viewpoints, despite having higher reconstruction errors, exhibit smaller gradient magnitudes. This significantly lowers the average gradient value, making it difficult to "split" or "clone" the Gaussian.
![2](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/53f2ad61-03c6-4acc-920a-644a402d2377)

We address this issue by using a weighted average approach that prioritizes viewpoints with larger absolute errors and higher gradients. Specifically, due to the mathematical properties of Gaussian distributions, the gradient at a viewpoint for a Gaussian is primarily contributed by a few pixels near the center of the Gaussian. For larger Gaussians, when the central point is projected onto screen space, there are more pixels involved in the calculations at this viewpoint. Using a pixel count weighted average allows for prioritization of such viewpoints. For smaller Gaussians, the number of pixels involved in calculations does not vary significantly across different viewpoints, so the impact of using a pixel count weighted average on smaller Gaussians is minimal.

**Comment by zhengzhang01** [comment]
Thank you for your interest in our work!

Our paper addresses the following issue: According to Formula 4 in the paper, during the initialization process of 3DGS, the radius of the Gaussian assigned to each point is determined based on the distance to the three nearest points. In regions where the initial Structure-from-Motion (SFM) point cloud is sparse, larger Gaussians are generated to fill these areas.

The original 3DGS determines whether a Gaussian should "split" or "clone" based on whether the average magnitude of the gradient in different Normalized Device Coordinates (NDC) views exceeds a threshold ($\frac{\sum{\parallel \mathbf{g}_i\parallel}}{\sum{1}} > {\tau}_{\mathrm{pos}}$).

We have found that this condition for point cloud growth does not work effectively for larger Gaussians, mainly for the following reason:

1. From a single viewpoint: Larger Gaussians experience severe gradient cancellation between different pixels within the same view. In contrast, even if smaller Gaussians undergo gradient cancellation, due to the mathematical differences in Gaussian distributions across pixels, the magnitude of gradients differs significantly, making the cancellation less severe.
![1](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/8f7b2314-00fb-4431-8e59-5065d3095f2b)

2. 1. From different viewpoints: Large Gaussians occupy more 3D space and thus involve more viewpoints in the same spatial location compared to smaller Gaussians. However, some of these viewpoints only contribute to the calculations at the edges. Due to the mathematical properties of Gaussian distributions and the occurrence of gradient cancellation, these viewpoints, despite having higher reconstruction errors, exhibit smaller gradient magnitudes. This significantly lowers the average gradient value, making it difficult to "split" or "clone" the Gaussian.
![2](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/6a762836-7265-49cb-a9d2-3f4803882464)
We address this issue by using a weighted average approach that prioritizes viewpoints with larger absolute errors and higher gradients. Specifically, due to the mathematical properties of Gaussian distributions, the gradient at a viewpoint for a Gaussian is primarily contributed by a few pixels near the center of the Gaussian. For larger Gaussians, when the central point is projected onto screen space, there are more pixels involved in the calculations at this viewpoint. Using a pixel count weighted average allows for prioritization of such viewpoints. For smaller Gaussians, the number of pixels involved in calculations does not vary significantly across different viewpoints, so the impact of using a pixel count weighted average on smaller Gaussians is minimal.

**Comment by zhengzhang01** [comment]
Thank you for your interest in our work!

Our paper addresses the following issue: According to Formula 4 in the paper, during the initialization process of 3D Gaussian Splatting (3DGS), the radius of the Gaussian assigned to each point is determined based on the distance to the three nearest points. In regions where the initial Structure-from-Motion (SFM) point cloud is sparse, larger Gaussians are generated to fill these areas.

The original 3DGS determines whether a Gaussian should "split" or "clone" based on whether the average magnitude of the gradient in different Normalized Device Coordinates (NDC) views exceeds a threshold ($\frac{\sum \|\mathbf{g}_i\|}{\sum 1} > \tau_{\mathrm{pos}}$).

We have found that this condition for point cloud growth does not work effectively for larger Gaussians, mainly for the following reason:

1. From a single viewpoint: Larger Gaussians experience severe gradient cancellation between different pixels within the same view. In contrast, even if smaller Gaussians undergo gradient cancellation, due to the mathematical differences in Gaussian distributions across pixels, the magnitude of gradients differs significantly, making the cancellation less severe.
![1](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/ebd9497d-e667-41f2-ba3b-c4dcd073bf1c)

2. From different viewpoints: Large Gaussians occupy more 3D space and thus involve more viewpoints in the same spatial location compared to smaller Gaussians. However, some of these viewpoints only contribute to the calculations at the edges. Due to the mathematical properties of Gaussian distributions and the occurrence of gradient cancellation, these viewpoints, despite having higher reconstruction errors, exhibit smaller gradient magnitudes. This significantly lowers the average gradient value, making it difficult to "split" or "clone" the Gaussian.
![2](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/a8b85cc8-4e51-4923-bdd9-c2c5a38c728e)

We address this issue by using a weighted average approach that prioritizes viewpoints with larger absolute errors and higher gradients. Specifically, due to the mathematical properties of Gaussian distributions, the gradient at a viewpoint for a Gaussian is primarily contributed by a few pixels near the center of the Gaussian. For larger Gaussians, when the central point is projected onto screen space, there are more pixels involved in the calculations at this viewpoint. Using a pixel count weighted average allows for prioritization of such viewpoints. For smaller Gaussians, the number of pixels involved in calculations does not vary significantly across different viewpoints, so the impact of using a pixel count weighted average on smaller Gaussians is minimal.

**Comment by zhengzhang01** [comment]
Thank you for your interest in our work!

Our paper addresses the following issue: According to Formula 4 in the paper, during the initialization process of 3DGS, the radius of the Gaussian assigned to each point is determined based on the distance to the three nearest points. In regions where the initial Structure-from-Motion (SFM) point cloud is sparse, larger Gaussians are generated to fill these areas.

The original 3DGS determines whether a Gaussian should "split" or "clone" based on whether the average magnitude of the gradient in different Normalized Device Coordinates (NDC) views exceeds a threshold (`$\frac{\sum \|\mathbf{g}_i\|}{\sum 1} > \tau_{\mathrm{pos}}$`).

We have found that this condition for point cloud growth does not work effectively for larger Gaussians, mainly for the following reason:

1. From a single viewpoint: Larger Gaussians experience severe gradient cancellation between different pixels within the same view. In contrast, even if smaller Gaussians undergo gradient cancellation, due to the mathematical differences in Gaussian distributions across pixels, the magnitude of gradients differs significantly, making the cancellation less severe.
![1](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/d6ca6767-e838-4180-9189-b424562ea8d0)

2. From different viewpoints: Large Gaussians occupy more 3D space and thus involve more viewpoints in the same spatial location compared to smaller Gaussians. However, some of these viewpoints only contribute to the calculations at the edges. Due to the mathematical properties of Gaussian distributions and the occurrence of gradient cancellation, these viewpoints, despite having higher reconstruction errors, exhibit smaller gradient magnitudes. This significantly lowers the average gradient value, making it difficult to "split" or "clone" the Gaussian.
![2](https://github.com/zhengzhang01/Pixel-GS/assets/133135464/6aa62026-dd48-4cf2-8556-cf35f36a92e1)

We address this issue by using a weighted average approach that prioritizes viewpoints with larger absolute errors and higher gradients. Specifically, due to the mathematical properties of Gaussian distributions, the gradient at a viewpoint for a Gaussian is primarily contributed by a few pixels near the center of the Gaussian. For larger Gaussians, when the central point is projected onto screen space, there are more pixels involved in the calculations at this viewpoint. Using a pixel count weighted average allows for prioritization of such viewpoints. For smaller Gaussians, the number of pixels involved in calculations does not vary significantly across different viewpoints, so the impact of using a pixel count weighted average on smaller Gaussians is minimal.

**Comment by JIANG-CX** [comment]
Thanks. Your reply has resolved my confusion.
